# Generated by Django 3.1.4 on 2021-01-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210120_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(default='ENG-1611139567', max_length=20, verbose_name='Number_order'),
        ),
    ]
