# Generated by Django 3.1.4 on 2021-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210120_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(default='EAJ-1611150396', max_length=20, verbose_name='Number_order'),
        ),
    ]
