# Generated by Django 3.1.4 on 2021-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210120_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(default='PBM-1611163248', max_length=20, verbose_name='Number_order'),
        ),
    ]
