# Generated by Django 3.1.4 on 2021-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210121_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.CharField(default='CEY-1611316064', max_length=20, verbose_name='Number_order'),
        ),
    ]
